<?php
$PATH_extension = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('locate');
return array(

	## generated

	'Bitmotion\Locate\Tools\IP' => $PATH_extension.'Classes/Tools/IP.php',
	'Bitmotion\Locate\FactProvider\Typo3Page' => $PATH_extension.'Classes/FactProvider/Typo3Page.php',
	'Bitmotion\Locate\FactProvider\Exception' => $PATH_extension.'Classes/FactProvider/Exception.php',
	'Bitmotion\Locate\FactProvider\BrowserAcceptedLanguage' => $PATH_extension.'Classes/FactProvider/BrowserAcceptedLanguage.php',
	'Bitmotion\Locate\FactProvider\Environment' => $PATH_extension.'Classes/FactProvider/Environment.php',
	'Bitmotion\Locate\FactProvider\IP2Country' => $PATH_extension.'Classes/FactProvider/IP2Country.php',
	'Bitmotion\Locate\FactProvider\Constants' => $PATH_extension.'Classes/FactProvider/Constants.php',
	'Bitmotion\Locate\FactProvider\AbstractFactProvider' => $PATH_extension.'Classes/FactProvider/AbstractFactProvider.php',
	'Bitmotion\Locate\FactProvider\FactProviderInterface' => $PATH_extension.'Classes/FactProvider/FactProviderInterface.php',
	'Bitmotion\Locate\Reviewer\ReviewerInterface' => $PATH_extension.'Classes/Reviewer/ReviewerInterface.php',
	'Bitmotion\Locate\Reviewer\Exception' => $PATH_extension.'Classes/Reviewer/Exception.php',
	'Bitmotion\Locate\Reviewer\AbstractReviewer' => $PATH_extension.'Classes/Reviewer/AbstractReviewer.php',
	'Bitmotion\Locate\Log\Formatter\Firebug' => $PATH_extension.'Classes/Log/Formatter/Firebug.php',
	'Bitmotion\Locate\Log\Formatter\Simple' => $PATH_extension.'Classes/Log/Formatter/Simple.php',
	'Bitmotion\Locate\Log\Formatter\FormatterInterface' => $PATH_extension.'Classes/Log/Formatter/FormatterInterface.php',
	'Bitmotion\Locate\Log\Formatter\Xml' => $PATH_extension.'Classes/Log/Formatter/Xml.php',
	'Bitmotion\Locate\Log\Exception' => $PATH_extension.'Classes/Log/Exception.php',
	'Bitmotion\Locate\Log\Filter\Message' => $PATH_extension.'Classes/Log/Filter/Message.php',
	'Bitmotion\Locate\Log\Filter\Suppress' => $PATH_extension.'Classes/Log/Filter/Suppress.php',
	'Bitmotion\Locate\Log\Filter\Priority' => $PATH_extension.'Classes/Log/Filter/Priority.php',
	'Bitmotion\Locate\Log\Filter\FilterInterface' => $PATH_extension.'Classes/Log/Filter/FilterInterface.php',
	'Bitmotion\Locate\Log\Logger' => $PATH_extension.'Classes/Log/Logger.php',
	'Bitmotion\Locate\Log\Writer\AbstractWriter' => $PATH_extension.'Classes/Log/Writer/AbstractWriter.php',
	'Bitmotion\Locate\Log\Writer\Db' => $PATH_extension.'Classes/Log/Writer/Db.php',
	'Bitmotion\Locate\Log\Writer\Firebug' => $PATH_extension.'Classes/Log/Writer/Firebug.php',
	'Bitmotion\Locate\Log\Writer\Memory' => $PATH_extension.'Classes/Log/Writer/Memory.php',
	'Bitmotion\Locate\Log\Writer\Stream' => $PATH_extension.'Classes/Log/Writer/Stream.php',
	'Bitmotion\Locate\Log\Writer\Null' => $PATH_extension.'Classes/Log/Writer/Null.php',
	'Bitmotion\Locate\Log\Writer\Mail' => $PATH_extension.'Classes/Log/Writer/Mail.php',
	'Bitmotion\Locate\Log\Writer\Mock' => $PATH_extension.'Classes/Log/Writer/Mock.php',
	'Bitmotion\Locate\Exception' => $PATH_extension.'Classes/Exception.php',
	'Bitmotion\Locate\Judge\AbstractJudge' => $PATH_extension.'Classes/Judge/AbstractJudge.php',
	'Bitmotion\Locate\Judge\AndCondition' => $PATH_extension.'Classes/Judge/AndCondition.php',
	'Bitmotion\Locate\Judge\Fixed' => $PATH_extension.'Classes/Judge/Fixed.php',
	'Bitmotion\Locate\Judge\Exception' => $PATH_extension.'Classes/Judge/Exception.php',
	'Bitmotion\Locate\Judge\JudgeInterface' => $PATH_extension.'Classes/Judge/JudgeInterface.php',
	'Bitmotion\Locate\Judge\Decision' => $PATH_extension.'Classes/Judge/Decision.php',
	'Bitmotion\Locate\Processor\Court' => $PATH_extension.'Classes/Processor/Court.php',
	'Bitmotion\Locate\Processor\ProcessorInterface' => $PATH_extension.'Classes/Processor/ProcessorInterface.php',
	'Bitmotion\System\Autoloader' => $PATH_extension.'Classes/System/Autoloader.php',
	'Bitmotion\Locate\Action\ActionInterface' => $PATH_extension.'Classes/Action/ActionInterface.php',
	'Bitmotion\Locate\Action\Dummy' => $PATH_extension.'Classes/Action/Dummy.php',
	'Bitmotion\Locate\Action\HelloWorld' => $PATH_extension.'Classes/Action/HelloWorld.php',
	'Bitmotion\Locate\Action\TicTacToe' => $PATH_extension.'Classes/Action/TicTacToe.php',
	'Bitmotion\Locate\Action\AbstractAction' => $PATH_extension.'Classes/Action/AbstractAction.php',
	'Bitmotion\Locate\Action\Exception' => $PATH_extension.'Classes/Action/Exception.php',
	'Bitmotion\Locate\Action\Redirect' => $PATH_extension.'Classes/Action/Redirect.php',
	'Bitmotion\Locate\Action\SetCookie' => $PATH_extension.'Classes/Action/SetCookie.php',

);
?>